# 实现步骤
这一节我们使用的是方法1
1. 设计情感计算函数pos、neg
2. 读取csv中的数据
3. 对text列计算pos、neg情感得分 
4. 保存结果df.to_csv()


**数据**
- output/reports.csv

**词典**
- data/dict/negative.txt
- data/dict/positive.txt

### 1. 设计情感计算函数
以情感分析为例，主要计算正面和负面的信息，所以设置了pos和neg两个函数。

如果想根据词典，计算更多种指标，那么一个指标可定义一个函数。

In [1]:
import jieba

#读取词典，生成正负情感词表
negs = open('data/dict/negative.txt', encoding='gbk').read().split('\n')
poss = open('data/dict/positive.txt', encoding='gbk').read().split('\n')

def pos(text):
    num = 0
    words = jieba.lcut(text)
    for word in words:
        if word in poss:
            num+=1
    return num

def neg(text):
    num = 0
    words = jieba.lcut(text)
    for word in words:
        if word in negs:
            num+=1
    return num

#text = '国际金融市场动荡，存在很大的投资风险'
#neg(text)

### 2. 读取csv中的数据
'output/reports.csv'

In [2]:
import pandas as pd

df = pd.read_csv('output/reports.csv')
df.head()

   name  year                                               text
0  四川长虹  2017  　　2017 年，面对复杂多变的外部环境和多重叠加的困难挑战，公司聚焦用户与产品，强化消费洞...
1  江苏吴中  2014  　　2014 年，正值公司成立二十周年，上市十五周年，在董事会带领下，公司经营管理团队与全体...
2  联美控股  2017  报告期内，公司实现营业收入 2,376,375,380.44 元，同比增长 16.24%，营...
3  华海药业  2016  第三节\t公司业务概要\n\n一、 报告期内公司所从事的主要业务、经营模式及行业情况说明\n...
4  江泉实业  2014  　　报告期内，全球经济形势复杂多变、复苏进程缓慢；我国宏观经济进入增速放缓、结构调整加剧的新...

### 3. 对text列计算情感得分
```python
df['pos_words_num'] = df['text'].apply(pos)
df['neg_words_num'] = df['text'].apply(neg)
```

In [6]:
def words_count(text):
    return len(jieba.lcut(text))

df['pos_words_num'] = df['text'].apply(pos)
df['neg_words_num'] = df['text'].apply(neg)
df['words_num'] = df['text'].apply(words_count)

df.head()

Building prefix dict from the default dictionary ...
Loading model from cache /var/folders/sc/3mnt5tgs419_hk7s16gq61p80000gn/T/jieba.cache
Loading model cost 0.870 seconds.
Prefix dict has been built successfully.

,name,year,text,pos_words_num,neg_words_num,words_num
0,四川长虹,2017,2017 年，面对复杂多变的外部环境和多重叠加的困难挑战，公司聚焦用户与产品，强化消费洞...,208,30,1837
1,江苏吴中,2014,2014 年，正值公司成立二十周年，上市十五周年，在董事会带领下，公司经营管理团队与全体...,115,17,1270
2,联美控股,2017,"报告期内，公司实现营业收入 2,376,375,380.44 元，同比增长 16.24%，营...",45,4,822
3,华海药业,2016,第三节\t公司业务概要\n\n一、 报告期内公司所从事的主要业务、经营模式及行业情况说明\n...,344,44,3634
4,江泉实业,2014,报告期内，全球经济形势复杂多变、复苏进程缓慢；我国宏观经济进入增速放缓、结构调整加剧的新...,36,19,455

### 4. 保存结果
df.to_csv()

In [7]:
df.to_csv('output/reports_excel_senti.csv', encoding='utf-8')