[![](https://img.shields.io/badge/cntext-文本分析库-blue?style=for-the-badge&logo=github)](https://github.com/hidadeng/cntext)

In [ ]:
!pip3 install cntext --upgrade

# 词共现矩阵
co_occurrence_matrix

共现的趋势，共现的倾向。

物以类聚，人以群分

相似的词更容易出现在一起。

In [3]:
import cntext as ct

documents = ["I go to school every day by bus .",
             "i go to theatre every night by bus"]

matrix = ct.co_occurrence_matrix(documents, 
                        window_size=2, 
                        lang='english')
matrix

         .  bus  by  day  every  go  i  night  school  theatre  to
.        0    1   1    0      0   0  0      0       0        0   0
bus      1    0   2    1      0   0  0      1       0        0   0
by       1    2   0    1      2   0  0      1       0        0   0
day      0    1   1    0      1   0  0      0       1        0   0
every    0    0   2    1      0   0  0      1       1        1   2
go       0    0   0    0      0   0  2      0       1        1   2
i        0    0   0    0      0   2  0      0       0        0   2
night    0    1   1    0      1   0  0      0       0        1   0
school   0    0   0    1      1   1  0      0       0        0   1
theatre  0    0   0    0      1   1  0      1       0        0   1
to       0    0   0    0      2   2  2      0       1        1   0

In [4]:
matrix.to_csv('output/共现矩阵.csv')

In [6]:
documents2 = ["编程很好玩",
             "Python是最好学的编程"]

ct.co_occurrence_matrix(documents2, 
                        window_size=2, 
                        lang='chinese')

Building prefix dict from the default dictionary ...
Dumping model to file cache /var/folders/sc/3mnt5tgs419_hk7s16gq61p80000gn/T/jieba.cache
Loading model cost 0.700 seconds.
Prefix dict has been built successfully.

        Python  好玩  学  很  是  最好  的  编程
Python       0   0  0  0  1   1  0   0
好玩           0   0  0  1  0   0  0   1
学            0   0  0  0  1   1  1   1
很            0   1  0  0  0   0  0   1
是            1   0  1  0  0   1  0   0
最好           1   0  1  0  1   0  1   0
的            0   0  1  0  0   1  0   1
编程           0   1  1  1  0   0  1   0

## gephi软件 把共现矩阵绘制成  [词语（人物）关系网络图]

# cntext库


计算机领域有一个算法叫做SO_PMI，互信息。简单的讲个体之间不是完全独立的，如果我们一开始设定少量的

- 初始正面种子词
- 初始负面种子词


程序采用**共现法**会按照“物以类聚人以群分”的思路，

- 根据初始正面种子词找到很多大概率为正面情感的候选词
- 根据初始负种子词找到很多大概率为负面情感的候选词

https://github.com/hidadeng/cntext



## 先配置环境-安装Microsoft Visual C++ 14

[安装python包出现报错：Microsoft Visual 14.0 or greater is required. 怎么办？](https://mp.weixin.qq.com/s/Be3oN_QAEqkZ_UII4xPllA)

In [1]:
!pip3 install cntext

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
Requirement already satisfied: cntext==1.6.5 in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (1.6.5)
Requirement already satisfied: matplotlib in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (from cntext==1.6.5) (3.5.1)
Requirement already satisfied: gensim==4.0.0 in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (from cntext==1.6.5) (4.0.0)
Requirement already satisfied: jieba in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (from cntext==1.6.5) (0.42.1)
Requirement already satisfied: pyecharts in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (from cntext==1.6.5) (1.6.2)
Requirement already satisfied: scikit-learn==1.0 in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (from cntext==1.6.5) (1.0)
Requirement already satisfied: mittens in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (from cntext==1.6.5) (0.2)
Requirement already satisfied: numpy==1.20.0 in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (from cntext==1.6.5) (1.20.0)
Requirement already satisfied: scipy>=0.18.1 in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (from gensim==4.0.0->cntext==1.6.5) (1.7.3)
Requirement already satisfied: smart-open>=1.8.1 in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (from gensim==4.0.0->cntext==1.6.5) (5.2.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (from scikit-learn==1.0->cntext==1.6.5) (2.2.0)
Requirement already satisfied: joblib>=0.11 in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (from scikit-learn==1.0->cntext==1.6.5) (1.1.0)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (from matplotlib->cntext==1.6.5) (21.0)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (from matplotlib->cntext==1.6.5) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (from matplotlib->cntext==1.6.5) (1.3.1)
Requirement already satisfied: pillow>=6.2.0 in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (from matplotlib->cntext==1.6.5) (9.0.1)
Requirement already satisfied: pyparsing>=2.2.1 in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (from matplotlib->cntext==1.6.5) (3.0.4)
Requirement already satisfied: python-dateutil>=2.7 in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (from matplotlib->cntext==1.6.5) (2.8.2)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (from matplotlib->cntext==1.6.5) (0.10.0)
Requirement already satisfied: six in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (from cycler>=0.10->matplotlib->cntext==1.6.5) (1.16.0)
Requirement already satisfied: simplejson in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (from pyecharts->cntext==1.6.5) (3.17.6)
Requirement already satisfied: jinja2 in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (from pyecharts->cntext==1.6.5) (3.1.1)
Requirement already satisfied: prettytable in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (from pyecharts->cntext==1.6.5) (2.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (from jinja2->pyecharts->cntext==1.6.5) (2.1.1)
Requirement already satisfied: wcwidth in /Library/Frameworks/anaconda3/lib/python3.9/site-packages (from prettytable->pyecharts->cntext==1.6.5) (0.2.5)

In [1]:
import cntext as ct
import os

sopmier = ct.SoPmi(cwd=os.getcwd(),
                   input_txt_file='data/sopmi_corpus.txt',  #原始数据，您的语料
                   seedword_txt_file= 'data/sopmi_seed_words.txt', #人工标注的初始种子词
                   lang='chinese')   

sopmier.sopmi()

Building prefix dict from the default dictionary ...
Loading model from cache /var/folders/sc/3mnt5tgs419_hk7s16gq61p80000gn/T/jieba.cache

Step 1/4:...Preprocess   Corpus ...

Loading model cost 0.526 seconds.
Prefix dict has been built successfully.

Step 2/4:...Collect co-occurrency information ...
Step 3/4:...Calculate   mutual information ...
Step 4/4:...Save    candidate words ...
Finish! used 55.03 s

5M原始数据，100个候选词，大概运行60+s。结果存放于output/sopmi_candi_words文件夹内